// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/Playground copy.vue')['default']
    Playgound: typeof import('./src/components/Playgound.vue')['default']
    Playground: typeof import('./src/components/Playground.vue')['default']
    PlaygroundVue: typeof import('./src/components/PlaygroundVue.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    ResponsiveContainer: typeof import('./src/components/ResponsiveContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
